### ISSUE TITLE
https://vue-multiselect.js.org Docs aren't working

### ISSUE THREAD

**Issue by mattelen** [shentao/vue-multiselect#1762]
![image](https://github.com/shentao/vue-multiselect/assets/9289772/f7f7d9e4-ba8d-4a30-8f2f-58b1dcfbdbe9)

**Comment by Maksym-Malchenko** [comment]
Use the web archive snapshot from 05.02.2024 as temporary solution⏳:
https://web.archive.org/web/20240205190637/https://vue-multiselect.js.org/

**Comment by irissiri7** [comment]
Any progress on this one?

**Comment by mattelen** [comment]
Who would have thought deploying docs would be such a mission. I'm trying to get this deploying on Github pages, however as a temp solution while I figure this out, I've deployed the latest version of the v3 docs here: https://6619064013a2f400792892a0--inspiring-kitten-cb3fdb.netlify.app/

**Comment by mattelen** [comment]
@akki-jat could I ask you to look after this? I'm about to be some days without a laptop so I can't finish this. You most likely know a bit more about Github Actions and workflows than myself.

I'm simply trying to get the contents on /docs hosted onto github pages, so then it should work at https://shentao.github.io/vue-multiselect/ & https://vue-multiselect.js.org/. At the moment, to create less "to do" for now, I'm building the site locally, so all Github actions needs to do is host the static site of /docs - however it doesn't seem to be working. (Future wise, we should have this build in the pipeline, like it did before)

The latest issue I have is that the latest Pull Request merge didn't run the deployment (https://github.com/shentao/vue-multiselect/deployments), so I'm not 100% sure why it didn't activate the run. 

We don't have access to the Github Pages settings because of how the repo has been setup, so if you need something changed, reach out to shentao. He suggested maybe checking this out: https://github.com/marketplace/actions/deploy-github-pages-site.

Worse comes to worse, if you can't get it working, maybe we look as a temp solutions like having the https://vue-multiselect.js.org domain pointed to the netlify hosted solution, then we can come up with how we want this hosted

I'll still have access to emails, so can still approve PLs, as you have been doing for me (thanks so much for that). 
Let me know your thoughts

**Comment by akki-jat** [comment]
https://shentao.github.io/vue-multiselect/ is reachable now, we are working on https://vue-multiselect.js.org.

**Comment by mattelen** [comment]
Docs are working now at https://vue-multiselect.js.org. Thanks specially to @akki-jat & @shentao for getting them back up and running

**Comment by Braintelligence** [comment]
Am I missing something or are v2 docs still not working? I get 404.

**Comment by benoitkopp** [comment]
Vue 2 docs are still down ?
